### ISSUE TITLE
error when i run mvn clean install

### ISSUE THREAD

**Issue by pwn3r1** [AlexProgrammerDE/ServerWrecker#1]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project serverwrecker-common: Fatal error compiling: invalid target release: 15 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :serverwrecker-common
'cmd' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AlexProgrammerDE** [comment]
You need at least Java 15+ to compile ServerWrecker.

**Comment by pwn3r1** [comment]
okay, thanks!
