### ISSUE TITLE
[SUGGESTION] Proxy Support, chat.

### ISSUE THREAD

**Issue by InfiniteCod3** [AlexProgrammerDE/ServerWrecker#108]
I see that it should support proxies, while i found no way to actually feed it the proxies, even looked through the source.
and also giving the bots the ability to chat custom messages would also be cool.

**Comment by Mixarar** [comment]
![image](https://user-images.githubusercontent.com/35892166/235376279-bd3972d7-f348-429e-b5b9-7c284b2e27f8.png)
you can use proxies? Although I do have issues with the development version, as it doesn't run on my pc.

**Comment by InfiniteCod3** [comment]
I meant the CLI version, thats for example used on linux, not the GUI one

**Comment by AlexProgrammerDE** [comment]
Accounts and proxies are on my list for needing a full remake. The system is way too inconsistent. Already did a few parts, but there's a bunch left.

**Comment by AlexProgrammerDE** [comment]
The plan is to create a system to import/export accounts and proxies into the current profile. There will likely be multiple features like checking whether proxies work and managing/authenticating accounts.

**Comment by AlexProgrammerDE** [comment]
I've decided I'll store them inside the profile, not globally. That way I have a bit more control and don't need to worry about broken/missing accounts that could be from other profiles.

**Comment by AlexProgrammerDE** [comment]
Additionally, the CLI now has flags to load accounts, proxies and profiles.

**Comment by AlexProgrammerDE** [comment]
This has now been fully implemented in both the CLI and GUI. Check it out!
