### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by mikessx** [AlexProgrammerDE/ServerWrecker#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your issue

The app works fine, but bots can't join the server.

The full log is attached.
[servermmamt.log](https://github.com/AlexProgrammerDE/ServerWrecker/files/11819731/servermmamt.log)

### ServerWrecker Version

1.0.1

### Java Version

java version "17.0.6" 2023-01-17 LTS

**Comment by AlexProgrammerDE** [comment]
This appears to be a issue with ViaVersion conversion. I do not have a lot of knowledge about the internal workings of ViaVersion. Maybe at a future point I can help, but not right now.

**Comment by AlexProgrammerDE** [comment]
Does the error still happen with the latest version of ServerWrecker?
