### ISSUE TITLE
Movement of bots

### ISSUE THREAD

**Issue by Widify-dev** [AlexProgrammerDE/ServerWrecker#140]
### Is there an existing feature request for this?

- [x] I have searched the existing feature requests

### Describe your feature request

The results of bots without their movement are not objective enough. I want more objective results due to the load on the chunks system. Do not forget about setting the speed of movement of bots :)

**Comment by AlexProgrammerDE** [comment]
Hello! What do you mean with objective results? What do you mean with speed?

**Comment by Widify-dev** [comment]
I know that bots can only jump, and therefore I suggest adding bots moving at different speeds so that the test results are more objective.

**Comment by AlexProgrammerDE** [comment]
This is getting a lot closer to reality as pathfinding is slowly getting better and movement operators like switching to forward, left, right, backward work fine so far.

**Comment by AlexProgrammerDE** [comment]
Movement has become very good with the recent switch to the mineflayer physics engine. My biggest worries like collision issues are finally resolved and commands for pathfinding and moving left, right, forward, backwards are also available now. I will close this issue as resolved once I've released a new version that has the major movement remake.
