### ISSUE TITLE
Improve/add docs for CLI

### ISSUE THREAD

**Issue by InfiniteCod3** [AlexProgrammerDE/ServerWrecker#147]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

It would be good if docs for the CLI version would be added as i get confused trying to start it/configure it.

**Comment by AlexProgrammerDE** [comment]
Resolved thanks to #151 and https://github.com/AlexProgrammerDE/ServerWrecker/commit/f4ea6caaf1352294eb3e0db893bd4fa5ecd55c12
