### ISSUE TITLE
Add easymc.io api for alts

### ISSUE THREAD

**Issue by Dannyx1604** [AlexProgrammerDE/ServerWrecker#149]
### Is there an existing feature request for this?

- [x] I have searched the existing feature requests

### Describe your feature request

Maybe add a way to log in with easymc.io alts for bot accounts

**Comment by AlexProgrammerDE** [comment]
For future reference: https://easymc.io/api

**Comment by AlexProgrammerDE** [comment]
A prototype for this is implemented in dev builds. I still need to look into verifying whether everything works as expected.

**Comment by AlexProgrammerDE** [comment]
Seems to work fine, You can get EasyMC starting 1.3.0
