### ISSUE TITLE
Reproducing precise movements like a normal player

### ISSUE THREAD

**Issue by Widify-dev** [AlexProgrammerDE/ServerWrecker#222]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

At the moment, anti-cheats (GrimAC, Vulcan and others) detect bots as violators. Even when they are just standing there is a BadPackets related check complaining about them. So in order to test with bots now, then you need to turn off anti-cheat for them. Anti-cheats also have an impact on the server load, at least on IO, and at most on the main thread.

**Comment by AlexProgrammerDE** [comment]
I'm planning to port the mineflayer physics engine to ServerWrecker this week. That'll be as good as it can currently get.

**Comment by Widify-dev** [comment]
> I'm planning to port the mineflayer physics engine to ServerWrecker this week. That'll be as good as it can currently get.

Very good!

**Comment by AlexProgrammerDE** [comment]
The PR for mineflayer physics has been merged. I put a lot of focus on using the calculations vanilla uses and also improved packets as well as collisions. The movement manager also supports ladders, elytras, bubble columns, water, better falling, server attributes, player effects, cobwebs, slime and honey blocks, better steps, random block offsets, soul sand and loads of other things now. Of course the bot doesn't have a elytra fly module now, but having it implemented in the movement manager is a good step towards that. You can get the new movement manager in the latest dev build now.
