### ISSUE TITLE
Issue when running 

### ISSUE THREAD

**Issue by InfiniteCod3** [AlexProgrammerDE/ServerWrecker#58]
root@Ubuntu-2204-jammy-amd64-base ~/ServerWrecker/core/build/libs # java -jar serverwrecker-core-all.jar

Exception: java.lang.ExceptionInInitializerError thrown from the UncaughtExceptionHandler in thread "main"

**Comment by InfiniteCod3** [comment]
nevermind im stupid :D

**Comment by InfiniteCod3** [comment]
Nevermind, im not stupid its broken :D

**Comment by AlexProgrammerDE** [comment]
Please reopen with full logs attached.
